name: build Gmeek
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, closed, deleted]
  issue_comment:
    types: [created, deleted]
  push:
    branches:
      - main
    paths:
      - 'config.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests PyGithub xpinyin feedgen jinja2 transliterate
      
      - name: Sync Forminit Comments
        env:
          FORMINIT_API_TOKEN: ${{ secrets.FORMINIT_API_TOKEN }}
        run: python sync_comments.py

      - name: Build Gmeek
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            ISSUE_NUM=${{ github.event.issue.number }}
          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            ISSUE_NUM=${{ github.event.issue.number }}
          else
            ISSUE_NUM=0
          fi
          python Gmeek.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} --issue_number $ISSUE_NUM
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit and Push docs
        run: |
          git add docs
          git commit -m "Build Gmeek: Update docs folder and sync comments" || echo "No changes to commit"
          git push
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
